version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/usr/src/orisa_api/
      - static_volume:/usr/src/orisa_api/staticfiles
    expose:
      - "8000"
    env_file: .env

  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/orisa_api/staticfiles

volumes:
  static_volume: