# Generated by Django 4.1.7 on 2023-03-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_vehicle_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='price',
        ),
    ]
