# Generated by Django 4.1.7 on 2023-02-27 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sight',
            name='tags',
            field=models.ManyToManyField(related_name='sights', to='sights.tag'),
        ),
        migrations.AddField(
            model_name='price',
            name='sight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sights.sight'),
        ),
    ]
