# Generated by Django 4.1.7 on 2023-02-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='price',
            name='kids_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
