# Generated by Django 4.1.7 on 2023-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0003_alter_price_adult_price_alter_price_kids_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
