# Generated by Django 4.1.7 on 2023-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0006_alter_price_kids_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='kids_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sight',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='sights', to='sights.tag'),
        ),
    ]
