# Generated by Django 4.1.7 on 2023-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0007_alter_price_kids_price_alter_sight_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='price',
            name='kids_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
