# Generated by Django 4.1.7 on 2023-03-04 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sights', '0008_alter_price_adult_price_alter_price_kids_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sight',
            name='timing',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
