# Generated by Django 4.1.7 on 2023-02-27 14:41

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='datetime_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='day',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 14, 41, 1, 455033, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
