# Generated by Django 4.1.7 on 2023-02-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_day_datetime_end_day_datetime_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='paid',
            new_name='adults',
        ),
        migrations.AddField(
            model_name='trip',
            name='kids',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
    ]
