# Generated by Django 4.1.7 on 2023-02-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_vehicle_price'),
        ('trips', '0004_alter_day_sight_alter_trip_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='guide',
        ),
        migrations.CreateModel(
            name='GuideTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.guide')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='guide',
            field=models.ManyToManyField(through='trips.GuideTrips', to='staff.guide'),
        ),
    ]
