# Generated by Django 4.1.7 on 2023-03-01 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_trip_guide_guidetrips_trip_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetrips',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 9, 39, 50, 413253, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
