# Generated by Django 4.1.7 on 2023-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_remove_day_datetime_end_remove_day_datetime_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daysight',
            options={'verbose_name': 'Sight'},
        ),
        migrations.AddField(
            model_name='daysight',
            name='extra',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
