# Generated by Django 4.1.7 on 2023-03-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_daysight_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysight',
            name='end_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daysight',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
