# Generated by Django 4.1.7 on 2023-03-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_daysight_end_at_alter_daysight_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='adults',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='free',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='kids',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
