# Generated by Django 4.1.7 on 2023-03-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_rename_guide_trip_guides_remove_trip_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='vehicle',
            new_name='vehicles',
        ),
    ]
