# Generated by Django 4.1.7 on 2023-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_vehicle_price'),
        ('trips', '0013_rename_vehicle_trip_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='guides',
            field=models.ManyToManyField(related_name='trips', through='trips.GuideTrips', to='staff.guide'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicles',
            field=models.ManyToManyField(related_name='trips', through='trips.VehiclesTrips', to='staff.vehicle'),
        ),
    ]
