# Generated by Django 4.1.7 on 2023-03-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_trip_guides_alter_trip_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='daysight',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daysight',
            name='kids_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
