# Generated by Django 4.1.7 on 2023-03-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_daysight_adult_price_daysight_kids_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysight',
            name='extra',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
