# Generated by Django 4.1.7 on 2023-03-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_alter_daysight_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysight',
            name='extra',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
