# Generated by Django 4.1.7 on 2023-03-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0018_rename_kids_price_daysight_kid_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='adults',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='free',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='kids',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
