# Generated by Django 4.1.7 on 2023-03-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_vehicle_price'),
        ('trips', '0019_trip_adults_trip_free_trip_kids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidetrips',
            name='date',
        ),
        migrations.RemoveField(
            model_name='guidetrips',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='guides',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicles',
        ),
        migrations.RemoveField(
            model_name='vehiclestrips',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vehiclestrips',
            name='trip',
        ),
        migrations.AddField(
            model_name='day',
            name='guides',
            field=models.ManyToManyField(through='trips.GuideTrips', to='staff.guide'),
        ),
        migrations.AddField(
            model_name='day',
            name='vehicles',
            field=models.ManyToManyField(through='trips.VehiclesTrips', to='staff.vehicle'),
        ),
        migrations.AddField(
            model_name='guidetrips',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestrips',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trips.day'),
            preserve_default=False,
        ),
    ]
