# Generated by Django 4.1.7 on 2023-03-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_remove_guidetrips_date_remove_guidetrips_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
