# Generated by Django 4.1.7 on 2023-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0021_alter_trip_commission_alter_trip_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysight',
            name='adult_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='daysight',
            name='adults_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daysight',
            name='kid_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='daysight',
            name='kids_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
